// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKY9ztAO-7lKGQOGmvvgm9xmC3nTKPwbk',
    appId: '1:568496657257:web:a6b29f7c94c7fd01a663f8',
    messagingSenderId: '568496657257',
    projectId: 'quiz-application-2ba15',
    authDomain: 'quiz-application-2ba15.firebaseapp.com',
    storageBucket: 'quiz-application-2ba15.appspot.com',
    measurementId: 'G-GL5MM5VPFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc02CDe-MKKQSoEBejqHzmFl7w91I3Jis',
    appId: '1:568496657257:android:46493d86949d20baa663f8',
    messagingSenderId: '568496657257',
    projectId: 'quiz-application-2ba15',
    storageBucket: 'quiz-application-2ba15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwD6ckt3svP3VB6xNg98f40Ri0DDg0tY',
    appId: '1:568496657257:ios:f6dcb955f63cbcd5a663f8',
    messagingSenderId: '568496657257',
    projectId: 'quiz-application-2ba15',
    storageBucket: 'quiz-application-2ba15.appspot.com',
    iosClientId: '568496657257-hpb3d1dm85s9u3pfm6icoqdenhvs70lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
